import { apiRequest } from "./globais.js";

const PLAYERS_ENDPOINT = "/jogadores";
const PERFORMANCE_ENDPOINT = "/desempenho";
const COLORS = ["#e53b46", "#48a8ff", "#36d996", "#ffc529", "#b77bff"];
const ATTRS = [["ataque", "ATQ"], ["defesa", "DEF"], ["velocidade", "VEL"], ["habilidade", "HAB"], ["passe", "PAS"]];
let jogadores = [], equipes = Array.from({length:5},()=>[]), numeroTimes = 5;
const $=id=>document.getElementById(id), num=v=>Number.isFinite(Number(v))?Number(v):0;
const norm=v=>String(v??"").normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/[^a-z0-9]/g,"");
const esc=v=>String(v??"").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/\"/g,"&quot;").replace(/'/g,"&#039;");
const initials=n=>{const p=String(n||"?").trim().split(/\s+/).filter(Boolean);return p.length>1?(p[0][0]+p[p.length-1][0]).toUpperCase():p[0].slice(0,2).toUpperCase()};
function avaliacao(j){const a=j?.avaliacao??j?.avaliacao_tecnica??j?.tecnica;if(a&&typeof a==="object")return a;return ATTRS.some(([k])=>j?.[k]!=null)?j:null}
function media(j){const a=avaliacao(j);return a?ATTRS.reduce((s,[k])=>s+num(a[k]),0)/5:null}
function totalTecnico(j){const a=avaliacao(j);return a?ATTRS.reduce((s,[k])=>s+num(a[k]),0):0}
function pontos(j){return num(j.pontos)}
function escolhido(id){return equipes.some(t=>t.some(j=>String(j.id)===String(id)))}
function timeDo(id){return equipes.findIndex(t=>t.some(j=>String(j.id)===String(id)))}
function mesclar(base,des){const id=new Map(des.map(j=>[String(j.id),j])),nome=new Map(des.map(j=>[norm(j.nome??j.name),j]));return base.map(j=>{const d=id.get(String(j.id))||nome.get(norm(j.nome??j.name));return {...j,...(d||{}),id:j.id??d?.id,nome:j.nome??d?.nome??d?.name??"Jogador sem nome"}})}
async function tentar(e){try{return await apiRequest(e)}catch(x){console.warn(e,x);return null}}
async function carregar(){try{const[b,d]=await Promise.all([tentar(PLAYERS_ENDPOINT),tentar(PERFORMANCE_ENDPOINT)]);const base=Array.isArray(b)?b:[],des=Array.isArray(d)?d:[];if(!base.length&&!des.length)throw Error("As APIs não retornaram jogadores.");jogadores=(base.length?mesclar(base,des):des).filter(j=>j.id!=null&&String(j.nome??j.name??"").trim());jogadores.sort((a,b)=>(media(b)??-1)-(media(a)??-1)||pontos(b)-pontos(a)||String(a.nome).localeCompare(String(b.nome),"pt-BR"));render();if($("status"))$("status").textContent=`${jogadores.length} jogadores carregados • seleção manual ativa.`}catch(e){console.error(e);if($("status"))$("status").textContent=`Erro ao carregar jogadores: ${e.message}`}}
function radar(j){const a=avaliacao(j);if(!a)return `<div class="radar radar-empty" aria-label="Sem avaliação técnica"><span>—</span></div>`;const vals=ATTRS.map(([k])=>Math.min(20,num(a[k]))),cx=40,cy=40,r=30,pts=vals.map((v,i)=>{const ang=-Math.PI/2+i*2*Math.PI/5,rr=r*(v/20);return `${(cx+Math.cos(ang)*rr).toFixed(1)},${(cy+Math.sin(ang)*rr).toFixed(1)}`}).join(" "),rings=[.5,.75,1].map(q=>ATTRS.map((_,i)=>{const ang=-Math.PI/2+i*2*Math.PI/5;return `${(cx+Math.cos(ang)*r*q).toFixed(1)},${(cy+Math.sin(ang)*r*q).toFixed(1)}`}).join(" "));const axes=ATTRS.map((_,i)=>{const ang=-Math.PI/2+i*2*Math.PI/5;return `<line x1="40" y1="40" x2="${(cx+Math.cos(ang)*r).toFixed(1)}" y2="${(cy+Math.sin(ang)*r).toFixed(1)}"/>`}).join("");return `<div class="radar" aria-label="Radar técnico"><svg viewBox="0 0 80 80" role="img"><g class="radar-grid">${rings.map(p=>`<polygon points="${p}"/>`).join("")}${axes}</g><polygon class="radar-data" points="${pts}"/></svg></div>`}
function render(){renderPlayers();renderTeams();renderSummary();if($("pickedCount"))$("pickedCount").textContent=equipes.reduce((s,t)=>s+t.length,0)}
function renderPlayers(){const q=norm($("searchPlayer")?.value||""),list=jogadores.filter(j=>!escolhido(j.id)&&(!q||norm(j.nome).includes(q)));if($("availableCount"))$("availableCount").textContent=list.length;if($("players"))$("players").innerHTML=list.length?list.map((j,i)=>playerCard(j,i)).join(""):'<div class="empty">Nenhum jogador disponível.</div>'}
function playerCard(j,i){const m=media(j);const buttons=Array.from({length:numeroTimes},(_,t)=>`<button class="pick" data-id="${esc(j.id)}" data-team="${t}" ${equipes[t].length>=7?"disabled":""} aria-label="Adicionar ao time ${t+1}" title="Adicionar ao time ${t+1}">${t+1}</button>`).join("");return `<article class="player-card" style="animation-delay:${Math.min(i*15,400)}ms"><div class="player-main">${radar(j)}<div class="player-info"><div class="player-name">${esc(j.nome)}</div><div class="player-meta">${pontos(j)} pts · ${num(j.vitorias)}V · ${num(j.gols)}G</div></div>${m!==null?`<div class="card-rating"><small>MÉDIA</small>${m.toFixed(1)}</div>`:`<div class="card-rating missing-rating">—</div>`}</div><div class="pick-row">${buttons}</div></article>`}
function renderTeams(){if(!$("teams"))return;$("teams").innerHTML=equipes.slice(0,numeroTimes).map((t,i)=>{const tech=t.reduce((s,j)=>s+totalTecnico(j),0),avg=t.length?tech/(t.length*5):0;const members=t.length?t.map(j=>`<div class="member"><div class="avatar">${esc(initials(j.nome))}</div><div class="member-name">${esc(j.nome)}<br><span class="player-meta">${media(j)!==null?media(j).toFixed(1):"sem avaliação"}</span></div><button class="remove" data-remove="${esc(j.id)}" title="Remover">×</button></div>`).join(""):'<div class="empty">Escolha os jogadores</div>';return `<article class="team" style="--team:${COLORS[i]}"><div class="team-head"><div class="team-number" style="color:${COLORS[i]}">${i+1}</div><div class="team-info"><div class="team-count">${t.length}/7${t.length>=7?" · COMPLETO":""}</div></div><div class="team-total">${tech}<small>${avg.toFixed(1)}</small></div></div><div class="members">${members}</div></article>`}).join("")}
function renderSummary(){if(!$("summary"))return;$("summary").innerHTML=equipes.slice(0,numeroTimes).map((t,i)=>`<div class="summary"><strong style="color:${COLORS[i]}">${i+1}</strong><span>${t.length}/7 · ${t.reduce((s,j)=>s+pontos(j),0)} pts · média ${(t.length?t.reduce((s,j)=>s+(media(j)??0),0)/t.length:0).toFixed(1)}</span></div>`).join("")}
function adicionar(id,t){const j=jogadores.find(x=>String(x.id)===String(id));if(!j||equipes[t].length>=7||escolhido(id))return;equipes[t].push(j);render();if($("status"))$("status").textContent=`${j.nome} → Time ${t+1}`}
function remover(id){const t=timeDo(id);if(t<0)return;const j=equipes[t].find(x=>String(x.id)===String(id));equipes[t]=equipes[t].filter(x=>String(x.id)!==String(id));render();if($("status"))$("status").textContent=`${j?.nome||"Jogador"} removido`}
function alterarNumero(){numeroTimes=Number($("teamCount").value);for(let i=numeroTimes;i<5;i++)equipes[i]=[];render()}
$("players")?.addEventListener("click",e=>{const b=e.target.closest("button[data-id]");if(b)adicionar(b.dataset.id,Number(b.dataset.team))});$("teams")?.addEventListener("click",e=>{const b=e.target.closest("button[data-remove]");if(b)remover(b.dataset.remove)});$("searchPlayer")?.addEventListener("input",renderPlayers);$("teamCount")?.addEventListener("change",alterarNumero);$("clearAll")?.addEventListener("click",()=>{equipes=Array.from({length:5},()=>[]);render()});carregar();