import { apiRequest } from "./globais.js";

const PLAYERS_ENDPOINT = "/jogadores";
const PERFORMANCE_ENDPOINT = "/desempenho";
const SELECTION_ENDPOINT = "/montar-times";
const COLORS = ["#e53b46", "#48a8ff", "#36d996", "#ffc529", "#b77bff"];
const ATTRS = [["ataque", "ATQ"], ["defesa", "DEF"], ["velocidade", "VEL"], ["habilidade", "HAB"], ["passe", "PAS"]];
const POLL_MS = 1500;
let jogadores = [], equipes = Array.from({ length: 5 }, () => []), numeroTimes = 5, sincronizando = false, ultimoEstado = "";
const $ = id => document.getElementById(id);
const num = v => Number.isFinite(Number(v)) ? Number(v) : 0;
const norm = v => String(v ?? "").normalize("NFD").replace(/[\u0300-\u036f]/g, "").toLowerCase().replace(/[^a-z0-9]/g, "");
const esc = v => String(v ?? "").replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/\"/g, "&quot;").replace(/'/g, "&#039;");
const initials = n => { const p = String(n || "?").trim().split(/\s+/).filter(Boolean); return p.length > 1 ? (p[0][0] + p[p.length - 1][0]).toUpperCase() : p[0].slice(0, 2).toUpperCase(); };
function avaliacao(j) { const a = j?.avaliacao ?? j?.avaliacao_tecnica ?? j?.tecnica; if (a && typeof a === "object") return a; return ATTRS.some(([k]) => j?.[k] != null) ? j : null; }
function media(j) { const a = avaliacao(j); return a ? ATTRS.reduce((s, [k]) => s + num(a[k]), 0) / 5 : null; }
function totalTecnico(j) { const a = avaliacao(j); return a ? ATTRS.reduce((s, [k]) => s + num(a[k]), 0) : 0; }
function pontos(j) { return num(j.pontos); }
function escolhido(id) { return equipes.some(t => t.some(j => String(j.id) === String(id))); }
function mesclar(base, des) { const id = new Map(des.map(j => [String(j.id), j])), nome = new Map(des.map(j => [norm(j.nome ?? j.name), j])); return base.map(j => { const d = id.get(String(j.id)) || nome.get(norm(j.nome ?? j.name)); return { ...j, ...(d || {}), id: j.id ?? d?.id, nome: j.nome ?? d?.nome ?? d?.name ?? "Jogador sem nome" }; }); }
async function carregarJogadores() { const [b, d] = await Promise.all([apiRequest(PLAYERS_ENDPOINT), apiRequest(PERFORMANCE_ENDPOINT)]); const base = Array.isArray(b) ? b : [], des = Array.isArray(d) ? d : []; if (!base.length && !des.length) throw Error("As APIs não retornaram jogadores."); jogadores = (base.length ? mesclar(base, des) : des).filter(j => j.id != null && String(j.nome ?? j.name ?? "").trim()); jogadores.sort((a, b) => (media(b) ?? -1) - (media(a) ?? -1) || pontos(b) - pontos(a) || String(a.nome).localeCompare(String(b.nome), "pt-BR")); }
function radar(j) { const a = avaliacao(j); if (!a) return `<div class="radar radar-empty" aria-label="Sem avaliação técnica"><span>—</span></div>`; const vals = ATTRS.map(([k]) => Math.min(20, num(a[k]))), cx = 40, cy = 40, r = 30, point = (ang, rr) => `${(cx + Math.cos(ang) * rr).toFixed(1)},${(cy + Math.sin(ang) * rr).toFixed(1)}`, pts = vals.map((v, i) => point(-Math.PI / 2 + i * 2 * Math.PI / 5, r * (v / 20))).join(" "), rings = [.5, .75, 1].map(q => ATTRS.map((_, i) => point(-Math.PI / 2 + i * 2 * Math.PI / 5, r * q)).join(" ")); const axes = ATTRS.map((_, i) => { const ang = -Math.PI / 2 + i * 2 * Math.PI / 5; return `<line x1="40" y1="40" x2="${(cx + Math.cos(ang) * r).toFixed(1)}" y2="${(cy + Math.sin(ang) * r).toFixed(1)}"/>`; }).join(""); return `<div class="radar" aria-label="Radar técnico"><svg viewBox="0 0 80 80" role="img"><g class="radar-grid">${rings.map(p => `<polygon points="${p}"/>`).join("")}${axes}</g><polygon class="radar-data" points="${pts}"/></svg></div>`; }
function estadoAtual(data) { return JSON.stringify((data?.selecoes || []).map(s => [s.jogador_id, s.time_num, s.ordem])); }
function aplicarEstado(data) { const selecoes = Array.isArray(data?.selecoes) ? data.selecoes : [], mapa = new Map(jogadores.map(j => [String(j.id), j])), novas = Array.from({ length: 5 }, () => []); for (const s of selecoes) { const jogador = mapa.get(String(s.jogador_id)), time = Number(s.time_num) - 1; if (jogador && time >= 0 && time < 5 && novas[time].length < 7) novas[time].push(jogador); } equipes = novas; }
async function sincronizar({ silent = true } = {}) { if (sincronizando) return; sincronizando = true; try { const data = await apiRequest(SELECTION_ENDPOINT); const estado = estadoAtual(data); if (estado !== ultimoEstado) { aplicarEstado(data); ultimoEstado = estado; render(); } if ($("syncStatus")) { $("syncStatus").textContent = "● Online · seleção compartilhada"; $("syncStatus").classList.remove("offline"); } } catch (e) { console.warn("Falha na sincronização:", e); if ($("syncStatus")) { $("syncStatus").textContent = "● Reconectando…"; $("syncStatus").classList.add("offline"); } if (!silent && $("status")) $("status").textContent = `Erro de sincronização: ${e.message}`; } finally { sincronizando = false; } }
async function carregar() { try { await carregarJogadores(); await sincronizar({ silent: false }); render(); if ($("status")) $("status").textContent = `${jogadores.length} jogadores carregados • seleção online ativa.`; } catch (e) { console.error(e); if ($("status")) $("status").textContent = `Erro ao carregar jogadores: ${e.message}`; } }
function render() { renderPlayers(); renderTeams(); renderSummary(); if ($("pickedCount")) $("pickedCount").textContent = equipes.reduce((s, t) => s + t.length, 0); }
function renderPlayers() { const q = norm($("searchPlayer")?.value || ""), list = jogadores.filter(j => !escolhido(j.id) && (!q || norm(j.nome).includes(q))); if ($("availableCount")) $("availableCount").textContent = list.length; if ($("players")) $("players").innerHTML = list.length ? list.map((j, i) => playerCard(j, i)).join("") : '<div class="empty">Nenhum jogador disponível.</div>'; }
function playerCard(j, i) { const m = media(j), buttons = Array.from({ length: numeroTimes }, (_, t) => `<button class="pick" data-id="${esc(j.id)}" data-team="${t}" ${equipes[t].length >= 7 ? "disabled" : ""} aria-label="Adicionar ao time ${t + 1}" title="Adicionar ao time ${t + 1}">${t + 1}</button>`).join(""); return `<article class="player-card" style="animation-delay:${Math.min(i * 15, 400)}ms"><div class="player-main">${radar(j)}<div class="player-info"><div class="player-name">${esc(j.nome)}</div><div class="player-meta">${pontos(j)} pts · ${num(j.vitorias)}V · ${num(j.gols)}G</div></div>${m !== null ? `<div class="card-rating"><small>MÉDIA</small>${m.toFixed(1)}</div>` : `<div class="card-rating missing-rating">—</div>`}</div><div class="pick-row">${buttons}</div></article>`; }
function renderTeams() { if (!$("teams")) return; $("teams").innerHTML = equipes.slice(0, numeroTimes).map((t, i) => { const tech = t.reduce((s, j) => s + totalTecnico(j), 0), avg = t.length ? tech / (t.length * 5) : 0, members = t.length ? t.map(j => `<div class="member"><div class="avatar">${esc(initials(j.nome))}</div><div class="member-name">${esc(j.nome)}<br><span class="player-meta">${media(j) !== null ? media(j).toFixed(1) : "sem avaliação"}</span></div><button class="remove" data-remove="${esc(j.id)}" title="Remover">×</button></div>`).join("") : '<div class="empty">Escolha os jogadores</div>'; return `<article class="team" style="--team:${COLORS[i]}"><div class="team-head"><div class="team-number" style="color:${COLORS[i]}">${i + 1}</div><div class="team-info"><div class="team-count">${t.length}/7${t.length >= 7 ? " · COMPLETO" : ""}</div></div><div class="team-total">${tech}<small>${avg.toFixed(1)}</small></div></div><div class="members">${members}</div></article>`; }).join(""); }
function renderSummary() { if (!$("summary")) return; $("summary").innerHTML = equipes.slice(0, numeroTimes).map((t, i) => `<div class="summary"><strong style="color:${COLORS[i]}">${i + 1}</strong><span>${t.length}/7 · ${t.reduce((s, j) => s + pontos(j), 0)} pts · média ${(t.length ? t.reduce((s, j) => s + (media(j) ?? 0), 0) / t.length : 0).toFixed(1)}</span></div>`).join(""); }
async function adicionar(id, t) { const j = jogadores.find(x => String(x.id) === String(id)); if (!j || equipes[t].length >= 7 || escolhido(id)) return; try { if ($("status")) $("status").textContent = `Registrando ${j.nome} no Time ${t + 1}…`; await apiRequest(`${SELECTION_ENDPOINT}/selecionar`, { method: "POST", body: { jogador_id: Number(id), time_num: t + 1 } }); await sincronizar({ silent: false }); if ($("status")) $("status").textContent = `${j.nome} → Time ${t + 1} • visível para todos`; } catch (e) { console.error(e); await sincronizar(); if ($("status")) $("status").textContent = e.message.includes("já foi escolhido") ? `${j.nome} já foi escolhido por outro líder.` : `Não foi possível selecionar ${j.nome}: ${e.message}`; } }
async function remover(id) { const j = jogadores.find(x => String(x.id) === String(id)); if (!j) return; try { await apiRequest(`${SELECTION_ENDPOINT}/${encodeURIComponent(id)}`, { method: "DELETE" }); await sincronizar({ silent: false }); if ($("status")) $("status").textContent = `${j.nome} removido da seleção.`; } catch (e) { console.error(e); await sincronizar(); if ($("status")) $("status").textContent = `Não foi possível remover ${j.nome}: ${e.message}`; } }
function alterarNumero() { numeroTimes = Number($("teamCount").value); render(); }
async function limparTudo() { if (!confirm("Limpar a seleção atual para todos os dispositivos?")) return; try { await apiRequest(SELECTION_ENDPOINT, { method: "DELETE" }); await sincronizar({ silent: false }); if ($("status")) $("status").textContent = "Seleção limpa para todos."; } catch (e) { console.error(e); if ($("status")) $("status").textContent = `Não foi possível limpar: ${e.message}`; } }
$("players")?.addEventListener("click", e => { const b = e.target.closest("button[data-id]"); if (b) adicionar(b.dataset.id, Number(b.dataset.team)); });
$("teams")?.addEventListener("click", e => { const b = e.target.closest("button[data-remove]"); if (b) remover(b.dataset.remove); });
$("searchPlayer")?.addEventListener("input", renderPlayers);
$("teamCount")?.addEventListener("change", alterarNumero);
$("clearAll")?.addEventListener("click", limparTudo);
carregar();
setInterval(() => sincronizar(), POLL_MS);
